nav:
    - index.md
    - "*"
    - ":material/pencil-outline: Icones":
      - icones/icones.md
      - ":material/web: Icones a MaterialX": https://jaywhj.github.io/mkdocs-materialx/reference/icons-emojis.html
