site_name: "Material joapuiib"
site_author: "Joan Puigcerver Ibáñez"
site_email: "j.puigcerveribanez@edu.gva.es"
site_url: "https://joapuiib.github.io/mkdocs-material-joapuiib/"
dev_addr: 127.0.0.1:4567

repo_name: mkdocs-material-joapuiib
repo_url: https://github.com/joapuiib/mkdocs-material-joapuiib

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joapuiib
      name: joapuiib a GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joanpuigcerver/
      name: Joan Puigcerver a LinkedIn

draft_docs: |
  *_unpublished.md
  *_draft.md

exclude_docs: |
  *_excluded.md

theme:
  name: material-joapuiib
  under_construction: true
  icon:
    logo: octicons/book-16

  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.follow

  comments:
    repo: joapuiib/mkdocs-material-joapuiib
    repo_id: R_kgDOMUF9Jg
    category: General
    category_id: DIC_kwDOMUF9Js4CgyMF

  # Palette toggle for light mode
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - material/search
  - alias
  - awesome-pages # Navegació
  - drawio
  - exclude-search
  - encryptcontent:
      title_prefix: ''
      summary: 'Aquesta pàgina està protegida!'
      encryption_info_message: 'Introdueix la contrasenya per accedir al contingut protegit.'
      placeholder: 'Contrasenya'
      decryption_failure_message: 'Contrasenya incorrecta. Torna-ho a provar.'
      decryption_failure_timerange_message: 'Aquesta pàgina no està disponible en aquest moment.'
      input_class: 'md-encryption__input--password'
      remember_keys: false
      remember_password: false
      threshold_warning_min_entropy: 0
      show_content_on_serve: !ENV [SHOW_PROTECTED_CONTENT, true]
      serve_content_info_message: 'Aquest contingut sols està disponible en mode de desenvolupament.'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]


  - glightbox
  - macros
  # - material/social
  - material/tags
  - material-joapuiib/enviorment
  - material-joapuiib/sectionicons
  - material-joapuiib/filters
  - material-joapuiib/functions:
      load_file:
        files_dir: files
  - i18n:
      languages:
        - locale: ca
          default: true
          name: Valencià
          admonition_translations:
            note: Nota
            abstract: Resum
            tip: Consell
            success: Èxit
            question: Pregunta
            warning: Advertència
            failure: Error
            danger: Perill
            example: Exemple
            quote: Cita
            docs: Documentació
            solution: Solució
            important: Important
            notice: Fixa't
            prep: Preparació
            recommend: Recomanació
  - git-revision-date-localized # Després de i18n o falla

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - markdown_grid_tables
  - md_in_html
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.html
  - pymdownx.blocks.caption:
      auto: true
      types:
        - caption
        - name: figure-caption
          prefix: "Figura {}."
        - name: shadow-figure-caption
          prefix: "Figura {}."
          classes: shadow
        - name: "table-caption"
          prefix: "Taula {}."
        - name: attribution
          classes: "attribution spell-ignore"
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material_joapuiib.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.fancylists:
      inject_class: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 4
  - material_joapuiib.extensions.collapse_code:
      expand_text: ''
      expand_title: ''
      collapse_text: ''
      collapse_title: ''
