INHERIT: common_config.yml

site_name: "Material joapuiib"
dev_addr: 127.0.0.1:4567

repo_name: mkdocs-material-joapuiib
repo_url: https://github.com/joapuiib/mkdocs-material-joapuiib

theme:
  name: material-joapuiib
  cover: cipfp-mislata
  author: Joan Puigcerver Ibáñez
  email: j.puigcerveribanez@edu.gva.es
